# Nom du projet sur SonarCloud
sonar.projectKey=achrefhamzaoui_projetpi2eme

# Nom de l'organisation sur SonarCloud
sonar.organization=achrefhamzaoui

# Langage du projet (optionnel, ici JavaScript/Node.js)
sonar.language=js

# Répertoire contenant le code source
sonar.sources=.
